# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - dofbot_arm_controller
    - dofbot_gripper_controller

  dofbot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
  dofbot_gripper_controller:
    type: GripperCommand
    joints:
      - grip_joint
    action_ns: gripper_cmd
    default: true